// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/mazeta-mobile/MazetaMobileHome.tsx": () => import("../components/mockups/mazeta-mobile/MazetaMobileHome.tsx")
};
